### PR TITLE
Check READMEs in CI

### PR DESCRIPTION
**Pull request by jamwaffles**

### CODE REVIEW

**Comment by jamwaffles** [comment]
Some noise from the CI config - I simplified the sections a bit, which also allows the use of CircleCI parameters in the cache keys.

**Comment by rfuest** [comment]
We had previously talked about the `Cargo.lock` in the `eg-next` directory. I thought we had decided to not included it because we might want to enable periodic builds for the `eg-next` directory to make sure that the examples stay in sync with the development version of e-g.

**Comment by jamwaffles** [comment]
Ah ok, I forgot about that. I've removed the Cargo.* checksumming completely as it's pretty redundant now, even for non-master builds - something invalidates the Cargo cache during the run, so most dependencies are recompiled anyway.

**Comment by rfuest** [comment]
OK. The CI config looks good. Do you want to remove the `Cargo.lock` from `eg-next` and restore the `.gitignore`?

**Comment by jamwaffles** [comment]
All done, should be good to go now

**Review by rfuest — APPROVED** [review]
LGTM

**Pull request merged**
